/**
 * Core type definitions for productdrivers
 * All event types and payloads used across SDKs and backend
 */

/**
 * Event types that can be tracked
 */
export enum EventType {
  // Journey events
  JOURNEY_START = "JOURNEY_START",
  JOURNEY_COMPLETE = "JOURNEY_COMPLETE",
  STEP_VIEW = "STEP_VIEW",
  
  // Feature usage events
  FEATURE_USED = "FEATURE_USED",
  
  // Satisfaction events
  JOURNEY_SATISFACTION = "JOURNEY_SATISFACTION",
  
  // User behavior events
  USER_BEHAVIOR = "USER_BEHAVIOR",
  
  // Custom events
  CUSTOM = "CUSTOM",
}

/**
 * Base event payload that all events must include
 */
export interface BaseEventPayload {
  /** The project API key */
  projectKey: string;
  
  /** Optional user identifier */
  userId?: string;
  
  /** Session identifier (auto-generated by SDK if not provided) */
  sessionId?: string;
  
  /** Timestamp in milliseconds (auto-generated if not provided) */
  ts?: number;
  
  /** Additional metadata */
  meta?: Record<string, unknown>;
}

/**
 * Journey-specific event payload
 */
export interface JourneyEventPayload extends BaseEventPayload {
  event: EventType.JOURNEY_START | EventType.JOURNEY_COMPLETE | EventType.STEP_VIEW;
  
  /** Journey identifier (e.g., "checkout", "onboarding") */
  journey: string;
  
  /** Step identifier within the journey (e.g., "payment", "shipping") */
  step?: string;
}

/**
 * Feature usage event payload
 */
export interface FeatureEventPayload extends BaseEventPayload {
  event: EventType.FEATURE_USED;
  
  /** Journey context where feature was used */
  journey?: string;
  
  /** Feature identifier (e.g., "filter_by_price", "help_tooltip") */
  feature: string;
  
  /** Optional numeric value associated with the feature */
  value?: number;
}

/**
 * Satisfaction event payload
 */
export interface SatisfactionEventPayload extends BaseEventPayload {
  event: EventType.JOURNEY_SATISFACTION;
  
  /** Journey being rated */
  journey: string;
  
  /** Satisfaction score (typically 1-5 or 1-10) */
  value: number;
  
  /** Optional verbatim feedback */
  feedback?: string;
}

/**
 * Custom event payload for flexible tracking
 */
export interface CustomEventPayload extends BaseEventPayload {
  event: EventType.CUSTOM;
  
  /** Custom event name */
  name: string;
  
  /** Journey context if applicable */
  journey?: string;
  
  /** Optional value */
  value?: number;
}

/**
 * User behavior event payload for automatic behavior tracking
 */
export interface UserBehaviorEventPayload extends BaseEventPayload {
  event: EventType.USER_BEHAVIOR;
  
  /** Behavior type (e.g., 'rage_click', 'dead_click', 'scroll_depth') */
  behaviorType: string;
  
  /** Journey context where behavior occurred */
  journey?: string;
  
  /** Step within journey */
  step?: string;
  
  /** Feature related to behavior */
  feature?: string;
  
  /** CSS selector of element */
  elementSelector?: string;
  
  /** Text content of element */
  elementText?: string;
  
  /** Page URL where behavior occurred */
  pageUrl?: string;
  
  /** Numeric value (scroll %, time seconds, click count, etc.) */
  value?: number;
}

/**
 * Union type of all possible event payloads
 */
export type TrackPayload = 
  | JourneyEventPayload 
  | FeatureEventPayload 
  | SatisfactionEventPayload 
  | CustomEventPayload
  | UserBehaviorEventPayload;

/**
 * Identify payload for linking sessions to users
 */
export interface IdentifyPayload {
  /** The project API key */
  projectKey: string;
  
  /** User identifier */
  userId: string;
  
  /** Session identifier to link */
  sessionId: string;
  
  /** User traits/properties to store */
  traits?: Record<string, unknown>;
}

/**
 * Batch track request (array of events)
 */
export interface BatchTrackPayload {
  projectKey: string;
  events: Omit<TrackPayload, 'projectKey'>[];
}

/**
 * API response structure
 */
export interface APIResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
}

/**
 * Database record types (for internal use)
 */

export interface Workspace {
  id: string;
  name: string;
  created_at: string;
  updated_at: string;
}

export interface Project {
  id: string;
  workspace_id: string;
  name: string;
  project_key: string;
  created_at: string;
  updated_at: string;
}

export interface User {
  id: string;
  project_id: string;
  user_ref: string; // External user ID
  traits: Record<string, unknown>;
  first_seen: string;
  last_seen: string;
}

export interface Session {
  id: string;
  project_id: string;
  session_ref: string; // Session UUID from SDK
  user_id?: string;
  started_at: string;
  last_activity: string;
}

export interface Event {
  id: string;
  project_id: string;
  user_id?: string;
  session_id?: string;
  event: EventType;
  journey?: string;
  step?: string;
  feature?: string;
  value?: number;
  meta?: Record<string, unknown>;
  created_at: string;
}

export interface Survey {
  id: string;
  project_id: string;
  name: string;
  question: string;
  scale_min: number;
  scale_max: number;
  trigger_on_journey?: string;
  is_active: boolean;
  created_at: string;
}

export interface SurveyResponse {
  id: string;
  project_id: string;
  survey_id: string;
  session_id: string;
  user_id?: string;
  journey?: string;
  score: number;
  feedback?: string;
  created_at: string;
}

/**
 * Aggregated statistics types
 */

export interface JourneyStats {
  id: string;
  project_id: string;
  journey: string;
  period_start: string;
  period_end: string;
  total_sessions: number;
  completed_sessions: number;
  completion_rate: number;
  avg_satisfaction?: number;
  created_at: string;
}

export interface FeatureStats {
  id: string;
  project_id: string;
  feature: string;
  journey?: string;
  period_start: string;
  period_end: string;
  usage_count: number;
  unique_sessions: number;
  created_at: string;
}

export interface DriverStats {
  id: string;
  project_id: string;
  feature: string;
  journey?: string;
  period_start: string;
  period_end: string;
  sessions_with_feature: number;
  sessions_without_feature: number;
  avg_satisfaction_with: number;
  avg_satisfaction_without: number;
  satisfaction_delta: number;
  created_at: string;
}

